/***************************************************************
 * SHOTTO SECURE FORMS — UNIFIED ENDPOINT
 * Supports:
 *   - Shotto Primary School: admission + contact
 *   - Shotto Barber Studio: booking + contact
 *
 * Receiver: shottofidelis2@gmail.com
 * Existing school website remains compatible because missing site_id
 * defaults to shotto-school.
 ***************************************************************/
const CONFIG={RECEIVER_EMAIL:'shottofidelis2@gmail.com',MAX_PER_10_MINUTES:3,MAX_GLOBAL_PER_HOUR:30,MAX_NAME:100,MAX_EMAIL:150,MAX_PHONE:30,MAX_SUBJECT:120,MAX_MESSAGE:2000,MAX_SHORT:160};
const SITES={
  'shotto-school':{name:'Shotto Primary School',accent:'#087443',forms:['admission','contact']},
  'shotto-barber':{name:'Shotto Barber Studio',accent:'#191919',forms:['booking','contact']}
};
function doGet(){return ContentService.createTextOutput(JSON.stringify({ok:true,status:'online',service:'Shotto Secure Forms'})).setMimeType(ContentService.MimeType.JSON)}
function doPost(e){var requestId='';try{if(!e||!e.parameter)return formFail('Invalid submission.',requestId,'VALIDATION');var p=e.parameter;requestId=clean(p.request_id||'');if(clean(p.website||p.companyWebsite||p._gotcha||''))return formSuccess('Submission received.',requestId);
var siteId=clean(p.site_id||'shotto-school').toLowerCase(),site=SITES[siteId];if(!site)return formFail('Invalid website source.',requestId,'VALIDATION');var formType=clean(p.form_type||p.formType||p.type||'contact').toLowerCase();if(site.forms.indexOf(formType)===-1)return formFail('Invalid form type.',requestId,'VALIDATION');
var name=clean(p.name||p.parent_name||p.parentName||p.guardian_name||p.guardianName||''),email=clean(p.email||''),phone=clean(p.phone||p.parent_phone||p.parentPhone||''),message=clean(p.message||p.notes||p.additional_message||p.additionalMessage||'');
if(!validText(name,2,CONFIG.MAX_NAME))return formFail('Please enter a valid name.',requestId,'VALIDATION');if(!validPhone(phone))return formFail('Please enter a valid phone number.',requestId,'VALIDATION');if(email&&!validEmail(email))return formFail('Please enter a valid email address.',requestId,'VALIDATION');if(message.length>CONFIG.MAX_MESSAGE)return formFail('Message is too long.',requestId,'VALIDATION');
var rate=checkRateLimit(siteId+'|'+(email||phone||name));if(!rate.ok)return formFail(rate.message,requestId,'RATE_LIMIT');if(MailApp.getRemainingDailyQuota()<=0)return formFail('Email service is temporarily unavailable. Please try again later.',requestId,'MAIL_QUOTA');
var submissionId='SHOTTO-'+Utilities.getUuid().replace(/-/g,'').substring(0,10).toUpperCase(),submittedAt=Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Africa/Dar_es_Salaam','dd MMM yyyy, HH:mm:ss');
if(formType==='contact')return handleContact(siteId,site,p,{requestId:requestId,submissionId:submissionId,submittedAt:submittedAt,name:name,email:email,phone:phone,message:message});
if(formType==='booking')return handleBooking(siteId,site,p,{requestId:requestId,submissionId:submissionId,submittedAt:submittedAt,name:name,email:email,phone:phone,message:message});
if(formType==='admission')return handleAdmission(siteId,site,p,{requestId:requestId,submissionId:submissionId,submittedAt:submittedAt,name:name,email:email,phone:phone,message:message});
return formFail('Unsupported request.',requestId,'VALIDATION');}catch(err){console.error(err);return formFail('We could not process your request at the moment. Please try again.',requestId,'SERVER_ERROR')}}
function handleContact(siteId,site,p,c){var subject=clean(p.subject||p.enquiry||p.topic||'General Enquiry');if(!validText(subject,2,CONFIG.MAX_SUBJECT)||!validText(c.message,2,CONFIG.MAX_MESSAGE))return formFail('Please complete the subject and message.',c.requestId,'VALIDATION');var fp=hash([siteId,'contact',c.name,c.email,c.phone,subject,c.message].join('|').toLowerCase());if(isDuplicate(fp))return formFail('This same message was already received recently.',c.requestId,'DUPLICATE');var fields=[['Name',c.name],['Phone',c.phone],['Email',c.email||'Not provided'],['Subject',subject],['Message',c.message]];sendSchoolEmail(site,{subject:'Website Enquiry - '+subject+' - '+c.submissionId,html:buildEmail(site,'New Website Enquiry','A new message has been submitted through the website.',c,fields),plain:plainText(site,'New Website Enquiry',c,fields),replyTo:c.email});rememberDuplicate(fp);return formSuccess('Thank you. Your message has been sent successfully.',c.requestId,c.submissionId)}
function handleBooking(siteId,site,p,c){var service=clean(p.service||''),date=clean(p.preferred_date||''),time=clean(p.preferred_time||''),barber=clean(p.preferred_barber||'Any Available Barber');var allowed=['Classic Haircut','Skin Fade','Kids Haircut','Beard Trim & Shape','Haircut + Beard','Premium Grooming','Afro Taper Fade','Afro Shape & Line-Up','High Top Fade','Curly / Afro Texture Finish'];if(allowed.indexOf(service)===-1)return formFail('Please choose a valid barber service.',c.requestId,'VALIDATION');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return formFail('Please choose a valid preferred date.',c.requestId,'VALIDATION');if(!validText(time,4,30)||barber.length>CONFIG.MAX_SHORT)return formFail('Please choose a valid preferred time.',c.requestId,'VALIDATION');var fp=hash([siteId,'booking',c.name,c.email,c.phone,service,date,time,barber,c.message].join('|').toLowerCase());if(isDuplicate(fp))return formFail('This same booking request was already received recently.',c.requestId,'DUPLICATE');var fields=[['Client Name',c.name],['Phone',c.phone],['Email',c.email||'Not provided'],['Service',service],['Preferred Date',date],['Preferred Time',time],['Preferred Barber',barber],['Notes',c.message||'No additional notes']];sendSchoolEmail(site,{subject:'Barber Booking - '+service+' - '+c.submissionId,html:buildEmail(site,'New Barber Booking Request','A client has requested an appointment.',c,fields),plain:plainText(site,'New Barber Booking Request',c,fields),replyTo:c.email});rememberDuplicate(fp);return formSuccess('Booking request sent successfully. The studio will contact you to confirm your appointment.',c.requestId,c.submissionId)}
function handleAdmission(siteId,site,p,c){var child=clean(p.child_name||p.childName||p.student_name||p.studentName||''),age=clean(p.child_age||p.childAge||p.age||''),klass=clean(p.class_applying||p.classApplying||p.class_name||p.className||p['class']||''),intake=clean(p.preferred_intake||p.preferredIntake||p.intake||'');if(!validText(child,2,CONFIG.MAX_NAME))return formFail("Please enter the child's name.",c.requestId,'VALIDATION');if(klass.length>CONFIG.MAX_SHORT||intake.length>CONFIG.MAX_SHORT)return formFail('Invalid admission selection.',c.requestId,'VALIDATION');var fp=hash([siteId,'admission',c.name,c.email,c.phone,child,age,klass,intake,c.message].join('|').toLowerCase());if(isDuplicate(fp))return formFail('This same admission request was already received recently.',c.requestId,'DUPLICATE');var fields=[['Parent / Guardian',c.name],['Phone',c.phone],['Email',c.email||'Not provided'],['Child Name',child],['Child Age',age||'Not provided'],['Class Applying For',klass||'Not provided'],['Preferred Intake',intake||'Not provided'],['Additional Message',c.message||'No additional message']];sendSchoolEmail(site,{subject:'Admission Application - '+child+' - '+c.submissionId,html:buildEmail(site,'New Admission Application','A parent or guardian has submitted an admission request.',c,fields),plain:plainText(site,'New Admission Application',c,fields),replyTo:c.email});rememberDuplicate(fp);return formSuccess('Application received successfully. Our admissions team will contact you shortly.',c.requestId,c.submissionId)}
function sendSchoolEmail(site,o){var mail={to:CONFIG.RECEIVER_EMAIL,subject:o.subject,body:o.plain,htmlBody:o.html,name:site.name+' Website'};if(o.replyTo&&validEmail(o.replyTo))mail.replyTo=o.replyTo;MailApp.sendEmail(mail)}
function buildEmail(site,title,subtitle,c,fields){var rows=fields.map(function(f){return '<tr><td style="padding:0 0 12px"><div style="background:#f7f7f7;border:1px solid #e6e6e6;border-radius:10px;padding:13px 15px"><div style="font:700 11px Arial;text-transform:uppercase;letter-spacing:.5px;color:#6b7280;margin-bottom:5px">'+escapeHtml(f[0])+'</div><div style="font:500 15px/23px Arial;color:#111827;white-space:pre-wrap;word-break:break-word">'+formatValue(f[1])+'</div></div></td></tr>'}).join('');return '<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#eeeeee;font-family:Arial,sans-serif"><table width="100%" cellspacing="0" cellpadding="0" style="background:#eeeeee"><tr><td align="center" style="padding:20px 10px"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fff;border-radius:14px;overflow:hidden"><tr><td style="background:'+site.accent+';padding:24px 22px;color:#fff"><div style="font:700 24px/31px Arial">'+escapeHtml(site.name)+'</div><div style="font:14px/21px Arial;color:#f2f2f2;margin-top:4px">Secure website form submission</div></td></tr><tr><td style="padding:23px 22px 8px"><div style="font:700 21px/28px Arial;color:#111827">'+escapeHtml(title)+'</div><div style="font:14px/22px Arial;color:#667085;margin-top:6px">'+escapeHtml(subtitle)+'</div></td></tr><tr><td style="padding:15px 22px 10px"><table width="100%" cellspacing="0" cellpadding="0" style="table-layout:fixed">'+rows+'</table></td></tr><tr><td style="padding:8px 22px 24px"><div style="border-top:1px solid #e5e7eb;padding-top:16px;font:13px/21px Arial;color:#667085"><strong style="color:#111827">Submission ID:</strong> '+escapeHtml(c.submissionId)+'<br><strong style="color:#111827">Submitted:</strong> '+escapeHtml(c.submittedAt)+'</div></td></tr></table></td></tr></table></body></html>'}
function plainText(site,title,c,fields){return site.name+'\n'+title+'\n\n'+fields.map(f=>f[0]+': '+f[1]).join('\n')+'\n\nSubmission ID: '+c.submissionId+'\nSubmitted: '+c.submittedAt}
function checkRateLimit(identity){var lock=LockService.getScriptLock();try{lock.waitLock(5000);var props=PropertiesService.getScriptProperties(),now=Date.now(),g=parseTimes(props.getProperty('rate_global')).filter(t=>now-t<3600000);if(g.length>=CONFIG.MAX_GLOBAL_PER_HOUR)return{ok:false,message:'Too many submissions have been received. Please try again later.'};var key='rate_'+hash(identity),u=parseTimes(props.getProperty(key)).filter(t=>now-t<600000);if(u.length>=CONFIG.MAX_PER_10_MINUTES)return{ok:false,message:'You have submitted several forms recently. Please wait a few minutes and try again.'};g.push(now);u.push(now);props.setProperty('rate_global',JSON.stringify(g));props.setProperty(key,JSON.stringify(u));return{ok:true}}catch(err){console.error('Rate limit error',err);return{ok:true}}finally{try{lock.releaseLock()}catch(ignore){}}}
function isDuplicate(fp){return CacheService.getScriptCache().get('dup_'+fp)==='1'}function rememberDuplicate(fp){CacheService.getScriptCache().put('dup_'+fp,'1',300)}function hash(v){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v).toLowerCase().trim(),Utilities.Charset.UTF_8).map(function(b){var x=(b+256)%256;return('0'+x.toString(16)).slice(-2)}).join('').substring(0,24)}function parseTimes(v){if(!v)return[];try{var d=JSON.parse(v);return Array.isArray(d)?d.filter(x=>typeof x==='number'):[]}catch(e){return[]}}function validText(v,min,max){var n=String(v||'').trim().length;return n>=min&&n<=max}function validEmail(v){return !!v&&v.length<=CONFIG.MAX_EMAIL&&/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(v)}function validPhone(v){if(!v||v.length>CONFIG.MAX_PHONE)return false;return /^\+?[0-9]{8,15}$/.test(v.replace(/[\s\-\(\)\.]/g,''))}function clean(v){return v==null?'':String(v).replace(/\u0000/g,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').trim()}function escapeHtml(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function formatValue(v){return escapeHtml(v==null||v===''?'Not provided':String(v)).replace(/\n/g,'<br>')}
function formResponse(data,requestId){data.source='shotto-form';data.request_id=requestId||'';var payload=JSON.stringify(data).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');var html='<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><script>(function(){var data='+payload+';try{window.parent.postMessage(data,"*")}catch(e){}try{window.top.postMessage(data,"*")}catch(e){}document.body.textContent=data.ok?"Sent successfully":"Not sent";})();<\/script></body></html>';return HtmlService.createHtmlOutput(html).setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}function formSuccess(message,requestId,submissionId){return formResponse({ok:true,message:message,submissionId:submissionId||''},requestId)}function formFail(message,requestId,code){return formResponse({ok:false,code:code||'ERROR',message:message},requestId)}
